  name: Node.js CI
  on:
     push:
       branches: 
         - master
  jobs:
    build:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [14.x]
          # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
      steps:
        - name: checkout
          uses: actions/checkout@master
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3.0.0
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Install
          run: npm  install
        # - name: Build
        #   run: npm run build
      #上传资源
        - name: copy file via ssh
          uses: appleboy/scp-action@master
          with:
            source: "./*"
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: Mm506045318
            target: ${{secrets.REMOTE_PATH_GPT}}
            EXCLUDE: "/dist/, /node_modules/"
            # rm: true
        